/// <reference types="nativewind/types" />

import 'react-native';

declare module 'react-native-paper' {
  interface Card {
    className?: string;
  }
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
